
body: |-
  ## Using the API

  ```js
  const protoFiles = require('google-proto-files')
  ```

  ### Get a directory path by executing as a function
  ```js
  protoFiles('logging', 'v2')
  // node_modules/google-proto-files/google/logging/v2
  ```

  ### Get a path to the entry proto file for a specific API version
  ```js
  protoFiles.pubsub.v1
  // node_modules/google-proto-files/google/pubsub/v1/pubsub.proto
  ```

  ### load|loadSync(fileName, [options])

  #### [options](https://github.com/dcodeIO/protobuf.js/blob/master/src/parse.js#L42-L44)

  #### Load a proto which depends on google common protos.
  ##### Asynchronously
  ```js
  protoFiles.load('path/to/file.proto').then(function(root) {
    const MyService = root.lookup('example.MyService')
  })
    ```

  ##### Synchronously
  ```js
  const root = protoFiles.loadSync('path/to/file.proto');
  const MyService = root.lookup('example.MyService');
  ```
